### PR TITLE
fix(kibbeh): fix logout button not working in mobile layout

### LINKED ISSUE #2489: Sign out button not working
**Describe the bug**
Sign out button doesn't do anything.

**To Reproduce**
1. Go to 'dogehouse'
2. Click on 'your profile'
3. Go to sign out

**Expected behavior**
It to sign out and show login page

**Screenshots**

**What device are you on?**
Chrome for Android

**Additional context**

### PR DESCRIPTION
**Pull request by junedkhatri31**
fix #2489

### CODE REVIEW

File: kibbeh/src/ui/mobile/MobileHeader/ProfileHeader.tsx [hunk 1]
```diff
@@ -93,6 +95,3 @@ export const ProfileHeader: React.FC<ProfileHeaderProps> = ({
     </div>
   );
 };
-function t(arg0: string): string {
```
Comment (goldyydev) [inline kibbeh/src/ui/mobile/MobileHeader/ProfileHeader.tsx:96]: That might've been my fault
