### PR TITLE
improve invite page and room 's setting, fix some issues

### LINKED ISSUE #1735: New Version Bug: Spacing in the room settings is kinda bad
image

### LINKED ISSUE #1769: New Version Bug: Long text doesn't break line on Homepage. (Without spaces)
**Describe the bug**
If a room has a long title/description text, supposedly more than 32 chars without spaces, then it won't break line. It extends view horizontally and moves out of the view.

**To Reproduce**
1. Create new room. Enter title/description text more than 32 chars. No spaces!
2. Go back to homepage.
3. Right panel extends outside of view.

**Expected behavior**
The description line should contain inside the view.

**Screenshots**
Image 1
Image 2

**What device are you on?**
Desktop

**Additional context**
Simple fix, add `line-break: anywhere;` to title and description tags. After fix applied to the tag:
Fix

### LINKED ISSUE #1780: New Version Bug: Discord & GitHub links on login page should open in a new tab
**Describe the bug**
Discord & GitHub links on the login page should open in a new tab

**To Reproduce**
Logout.
Click on Discord & Github links in the footer.

**Expected behavior**
Websites open in a new tab.

### PR DESCRIPTION
**Pull request by hisamafahri**
add title to invite page 

fixing spacing problem in room setting's modal

add margin in the bottom of voice settings page

fix #1780 

fix #1769

fix #1735 

**Voice setting's page (before)**
bm-before

**Voice setting's page (after)**
bm-after

**Room settings (before)**
setting-before

**Room settings (after)**
setting-after

**Invite page (before)**
invite-before

**Invite page (after)**
invite-after

### CODE REVIEW

**Comment by ghost** [comment]
lgtm

File: kibbeh/src/modules/room/InviteRoomPage.tsx [hunk 1]
```diff
@@ -149,12 +152,12 @@ export const InviteRoomPage: PageComponent<InviteRoomPageProps> = ({}) => {
         {room.isPrivate ? null : (
           <>
             {!navigator.share ? (
-              <div className={`text-2xl mb-2`}>
+              <div className={`text-primary-100 font-bold text-2xl mb-2 `}>
```
Comment (overlisted) [inline kibbeh/src/modules/room/InviteRoomPage.tsx:155]:
```suggestion
              <div className={`text-primary-100 font-bold text-2xl mb-2`}>
```

File: kibbeh/src/modules/user/FollowingPage.tsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ interface UserPageProps {}
 export const FollowingPage: PageComponent<UserPageProps> = ({}) => {
   return (
     <WaitForWsAndAuth>
-      <HeaderController embed={{}} title="Following" />
+      <HeaderController embed={{}} title="Peoples" />
```
Comment (overlisted) [inline kibbeh/src/modules/user/FollowingPage.tsx:17]: ?

**Review by overlisted — CHANGES_REQUESTED** [review]

File: kibbeh/src/modules/user/FollowingPage.tsx (hunk 2 above)
Comment (hisamafahri) [reply kibbeh/src/modules/user/FollowingPage.tsx]: Being honest, the `following` pages and `followers` page are combined into one and only have a different function. 

You can check to the [next.dogehouse.tv](next.dogehouse.tv) and go to the following and followers section. It's all have title: `Following | DogeHouse`.

So I generalized it into `Peoples | DogeHouse`, because I can't find a solution except creating separate pages for each one, (but the function is to messy for me).

Comment (overlisted) [reply kibbeh/src/modules/user/FollowingPage.tsx:17]: ok then peoples isn't grammatically correct
```suggestion
      <HeaderController embed={{}} title="People" />
```

Comment (hisamafahri) [reply kibbeh/src/modules/user/FollowingPage.tsx]: lgtm
