### PR TITLE
fix(kibbeh): add an error message in the UserPreviewModal

### LINKED ISSUE #2801: Undefined User Modal Values (block user)
**Describe the bug**
A user that blocks you has undefined for all values in the user modal.

**To Reproduce**
1. Get another user to ban you.
2. Click on their modal (in a room)
3. See error

**Expected behavior**
Perhaps show 'You have been blocked by this user.' (same as profile url).
Otherwise this looks like some server error etc.

**Screenshots**
https://i.imgur.com/0FMgel5.png

**What device are you on?**
Chrome 90, Windows 10

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by n3oney**
fix #2801

### CODE REVIEW

File: kibbeh/src/modules/room/UserPreviewModal.tsx [hunk 1]
```diff
@@ -225,9 +235,9 @@ const UserPreview: React.FC<{
 };
 
 export const UserPreviewModal: React.FC<JoinRoomAndGetInfoResponse> = ({
-  room,
-  users,
-}) => {
+                                                                         room,
```
Comment (amitojsingh366) [inline kibbeh/src/modules/room/UserPreviewModal.tsx]: what is this?

**Review by amitojsingh366 — CHANGES_REQUESTED** [review]

File: kibbeh/src/modules/room/UserPreviewModal.tsx (hunk 1 above)
Comment (n3oney) [reply kibbeh/src/modules/room/UserPreviewModal.tsx]: probably some weird quirk of the WebStorm formatter, I'll look around in the settings

Comment (n3oney) [reply kibbeh/src/modules/room/UserPreviewModal.tsx]: fixed
